version: "1"

tasks:
    build:
        desc: Build the app
        cmds:
        - GOFLAGS=-mod=mod go build -o bin/gopher-bot-discord main.go 

    run: 
        desc: Run the app
        cmds:
        - GOFLAGS=-mod=mod go run *.go

    bot:
        desc: Execute the bot
        cmds:
        - ./bin/gopher-bot-discord